version: '3.8'

services:
  finance-bot:
    build: .
    container_name: finance-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - PAYER_EMAIL=${PAYER_EMAIL}
      - RECIPIENT_DISPLAY_NAME=${RECIPIENT_DISPLAY_NAME}
      - OWNER_USER_ID=${OWNER_USER_ID}
      - SUPPORT_NAME=${SUPPORT_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - SUPPORT_PHONE=${SUPPORT_PHONE}
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  mysql:
    image: mysql:8.0
    container_name: finance-bot-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - bot-network

volumes:
  mysql_data:


networks:
  bot-network:
    driver: bridge
